<!DOCTYPE html>
<html lang="en">

<head>
<?php include 'include/Head.php'; ?>
    
    <title>Terms and Condition - Finixpay services private limited</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            line-height: 1.6;
        }
        h1 {
            text-align: center;
            color: #4CAF50;
            font-size: 28px;
            margin-bottom: 20px;
        }
        ol {
            margin-left: 20px;
            padding-left: 20px;
        }
        ol[type="A"] > li {
            margin-bottom: 15px;
            font-weight: bold;
            color: #333;
        }
        ol[type="A"] > li > ol[type="I"] > li {
            margin-bottom: 10px;
            font-weight: normal;
            color: #555;
        }
        ol[type="I"] > li > ol[type="1"] > li {
            margin-bottom: 8px;
            font-style: italic;
        }
        b {
            color: #4CAF50;
        }
        p {
            margin: 10px 0;
        }
        .highlight {
            background-color: #f9f9f9;
            padding: 10px;
            border-left: 4px solid #4CAF50;
        }
    </style>
</head>

<body class="body-wrapper">    
<?php include 'include/Preloader.php'; ?>

<?php include 'include/Header.php'; ?>

    <div class="page-banner-wrap text-center bg-cover" style="background-image: url('assets/img/page-banner.jpg')">
        <div class="container">
            <div class="page-heading text-white">
                <h1>Terms and Condition</h1>
            </div>
            <nav>
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index">Home</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Terms and Condition</li>
                </ol>
            </nav>
        </div>
    </div>

    <section class="contact-page-wrap section-padding">
        <div class="container">
        <p>This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder, as amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

        <p>This document is published in accordance with Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011, and governs the use of the domain <a href="https://finixpayservices.com" target="_blank">https://finixpayservices.com</a> ("Website"), including the related mobile site and mobile application ("Platform").</p>

        <h2>1. Platform Ownership</h2>
        <p>The Platform is owned by <strong>Finixpay Services Private Limited</strong>, headquartered at Narpatpur Narayanpur Dubakiya, Varanasi, India ("Platform Owner", "we", "us", "our").</p>

        <h2>2. Agreement to Terms</h2>
        <p>By accessing, browsing, or using the Platform, you agree to these Terms & Conditions ("Terms"). Please read them carefully before proceeding.</p>

        <h2>3. User Obligations</h2>
        <ul>
            <li>Provide accurate and complete registration information.</li>
            <li>Be responsible for all activities under your registered account.</li>
            <li>Pay applicable charges for using our services.</li>
        </ul>

        <h2>4. Warranties and Disclaimers</h2>
        <p>Neither we nor any third parties guarantee the accuracy, timeliness, performance, or completeness of the information provided. Your use of the Platform is at your own risk.</p>

        <h2>5. Proprietary Rights</h2>
        <p>All content, including design, layout, and graphics, is proprietary to us. Unauthorized use may lead to action under applicable laws.</p>

        <h2>6. Indemnification</h2>
        <p>You agree to indemnify and hold harmless the Platform Owner, its affiliates, and employees from claims or demands arising out of your breach of these Terms or violation of any laws.</p>

        <h2>7. Governing Law and Jurisdiction</h2>
        <p>These Terms are governed by the laws of India, and any disputes shall be subject to the exclusive jurisdiction of courts in Varanasi, Uttar Pradesh.</p>

        <h2>8. Force Majeure</h2>
        <p>We are not liable for failure to perform due to events beyond our control ("Force Majeure").</p>

        <h2>9. Contact Us</h2>
        <p>If you have any concerns or questions, please contact us using the information provided on our website.</p>
    </div>
    </section>

    <?php include 'include/Footer.php'; ?>

    <!--  ALl JS Plugins
    ====================================== -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/modernizr.min.js"></script>
    <script src="assets/js/jquery.easing.js"></script>
    <script src="assets/js/popper.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/isotope.pkgd.min.js"></script>
    <script src="assets/js/imageload.min.js"></script>
    <script src="assets/js/scrollUp.min.js"></script>
    <script src="assets/js/slick.min.js"></script>
    <script src="assets/js/slick-animation.min.js"></script>
    <script src="assets/js/magnific-popup.min.js"></script>
    <script src="assets/js/wow.min.js"></script>
    <script src="assets/js/metismenu.js"></script>
    <script src="assets/js/nice-select2.js"></script>
    <script src="assets/js/active.js"></script>
</body>

</html>